# Generated by Django 5.0.4 on 2024-04-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='subscription_name',
            new_name='Service_name',
        ),
    ]
