# Generated by Django 5.0.4 on 2024-04-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subscription_name_permission_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='Service_name',
            new_name='service_name',
        ),
    ]
