# Generated by Django 5.0.4 on 2024-04-22 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_service_name_permission_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='subscription_end_date',
        ),
        migrations.AddField(
            model_name='permission',
            name='date_of_purchase',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='permission',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='permission',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
