# Generated by Django 5.0.4 on 2024-04-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_permission_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='date_of_purchase',
        ),
    ]
