# Generated by Django 5.0.4 on 2024-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_permission_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='subscription_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
