# Generated by Django 5.0.4 on 2024-04-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_of_publication',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='profile',
        ),
    ]
