# Generated by Django 5.0.4 on 2024-04-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_service_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='Contacts',
            new_name='contacts',
        ),
    ]
