# Generated by Django 5.0.4 on 2024-04-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_rename_address_gym_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym', to='gyms.gym'),
        ),
    ]
