# Generated by Django 5.0.4 on 2024-04-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_service_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gym',
        ),
        migrations.AddField(
            model_name='gym',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym', to='gyms.service'),
        ),
    ]
