# Generated by Django 5.0.4 on 2024-04-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_remove_gym_service_gym_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='service',
        ),
        migrations.AddField(
            model_name='gym',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym', to='gyms.service'),
        ),
    ]
