# Generated by Django 5.0.4 on 2024-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_remove_service_gym_service_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gym',
        ),
        migrations.AddField(
            model_name='service',
            name='gym',
            field=models.ManyToManyField(related_name='gym', to='gyms.gym'),
        ),
    ]
