# Generated by Django 5.0.4 on 2024-04-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_remove_service_gym_service_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='gym',
            field=models.ManyToManyField(related_name='servicex', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboniment', to='gyms.service'),
        ),
    ]
