# Generated by Django 5.0.4 on 2024-04-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_alter_service_gym_alter_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
