# Generated by Django 5.0.4 on 2024-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0013_gym_image_service_image_subscription_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
